In [163]:

#Study of Numpy and its Function

In [162]:
import numpy as np

In [2]:
emp_salary=np.random.randint(8,70,10)

In [3]:
emp_salary

array([53, 39, 62, 46, 64, 13, 45, 29, 27, 25])

In [4]:
#set minimum and maximum salary using a_min and a_max 

In [9]:
np.clip(emp_salary,a_min=20,a_max=50)# if we use clip method then all maximum and minimum value we can set as per our use

array([50, 39, 50, 46, 50, 20, 45, 29, 27, 25])

In [10]:
#If you want to find actual salary which are less then or greater than some salary use np.where
#np.where gives index detail

In [16]:
print(np.where(emp_salary <25))

(array([5], dtype=int64),)


In [17]:
#If you want to see actual data, use index 

In [19]:
emp_salary[[1,4]]

array([39, 64])

In [20]:
#similarly you can  check for any condition (<,>,=,==,<=,>=)

In [21]:
#Reshaping Otherways

In [24]:
import numpy as np
from numpy.random import randint as ri

In [40]:
a=ri(1,99,30)
print(a)

[63 21 43 24 93 10 22 27 23 20 38 10  6 90 69 87 55  3 38 71 12 56 31 62
 31 96 76 14 41 57]


In [42]:
b=a.reshape(2,3,5)
print(b)

[[[63 21 43 24 93]
  [10 22 27 23 20]
  [38 10  6 90 69]]

 [[87 55  3 38 71]
  [12 56 31 62 31]
  [96 76 14 41 57]]]


In [44]:
c=a.reshape(6,5)
print(c)

[[63 21 43 24 93]
 [10 22 27 23 20]
 [38 10  6 90 69]
 [87 55  3 38 71]
 [12 56 31 62 31]
 [96 76 14 41 57]]


In [49]:
print("Minimum of a is ",c.min())
print("Maximum of a is ",c.max())

Minimum of a is  3
Maximum of a is  96


In [50]:
#Sorting 

In [57]:
m=ri(1,100,25).reshape(5,5) #matrix of random integer
print("\n 5 X 5 matrix of random integer \n",'-'*50,'\n',m)
print("\n Here is the sorted matrix along each row \n",'-'*50,'\n',np.sort(m))#default axis=1
print("\n Here is the sorted matrix along each column \n",'-'*50,'\n',np.sort(m,axis=0))


 5 X 5 matrix of random integer 
 -------------------------------------------------- 
 [[76 99 70 31 63]
 [95 99 51 19 61]
 [61 10 85 72 18]
 [98 73 13 93 83]
 [96 90 99 45 49]]

 Here is the sorted matrix along each row 
 -------------------------------------------------- 
 [[31 63 70 76 99]
 [19 51 61 95 99]
 [10 18 61 72 85]
 [13 73 83 93 98]
 [45 49 90 96 99]]

 Here is the sorted matrix along each column 
 -------------------------------------------------- 
 [[61 10 13 19 18]
 [76 73 51 31 49]
 [95 90 70 45 61]
 [96 99 85 72 63]
 [98 99 99 93 83]]


In [58]:
# Index and slicing

In [59]:
arr=np.arange(13,30)
print("Array",arr)

Array [13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [63]:
print("Element of 7th index is =",arr[7])

Element of 7th inex is = 20


In [65]:
print("Element of 3rd and 5th index is = ",arr[3:5])

Element of 3rd and 5th index is =  [16 17]


In [67]:
print("Element up to 4th index are :",arr[4:])

Element up to 4th index are : [17 18 19 20 21 22 23 24 25 26 27 28 29]


In [71]:
#Store arr in abc and check upto 4th index of abc

In [72]:
abc=arr[4:]
print(abc)

[17 18 19 20 21 22 23 24 25 26 27 28 29]


In [73]:
print("Element from last backwords : ",abc[-1::-2])

Element from last backwords :  [29 27 25 23 21 19 17]


In [78]:
print("7th elemets from last backword are : ",arr[-1:-8:-1])

7th elemets from last backword are :  [29 28 27 26 25 24 23]


In [80]:
print("Elements at 2nd 4th and 9th index are : ",arr[[2,4,9]])#Pass a list as a index to subset

Elements at 2nd 4th and 9th index are :  [15 17 22]


In [84]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.array(my_mat)
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [85]:
print("Entire row at index 2: ",mat[2])

Entire row at index 2:  [7 8 9]


In [90]:
print("Entire column at index  3:\n",mat[:,1:])

Entire column at index  3:
 [[2 3]
 [5 6]
 [8 9]]


In [102]:
print("\nSubsetting Sub-Matricss\n---------")
print("Matrics with row indices 1 and 2 and column indices 3 and 4\n",mat[1:2,1:2])


Subsetting Sub-Matricss
---------
Matrics with row indices 1 and 2 and column indices 3 and 4
 [[5]]


In [108]:
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [112]:
print(mat[0:2,[1,2]])

[[2 3]
 [5 6]]


In [113]:
#Update Matrix

In [114]:
print("Original Matrix \n\n",mat)

Original Matrix 

 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [115]:
mat[0,2]=200

In [116]:
mat

array([[  1,   2, 200],
       [  4,   5,   6],
       [  7,   8,   9]])

In [117]:
mat[1,0]=100

In [118]:
mat

array([[  1,   2, 200],
       [100,   5,   6],
       [  7,   8,   9]])

In [120]:
#Subsetting-So what is subsetting ? subsetting means when we wann to fetch only few dara from matrix then we use subsetting method.

In [121]:
mat=np.array(ri(10,100,15)).reshape(3,5)
print('Matrix of random 2 digit number \n------\n',mat)

Matrix of random 2 digit number 
------
 [[77 97 24 91 89]
 [24 98 70 25 35]
 [12 33 92 72 53]]


In [126]:
print("Elements greater than 50\n ",mat[mat>50])

Elements greater than 50
  [77 97 91 89 98 70 92 72 53]


In [128]:
print(np.where(mat==98))

(array([1], dtype=int64), array([1], dtype=int64))


In [129]:
#You can also use np.where to return some data based on condtion

In [131]:
age=50
np.where(age>68,'Retired','Still Working')

array('Still Working', dtype='<U13')

In [132]:
#Universal Functions

In [135]:
mat1=np.array(ri(1,10,9)).reshape(3,3)
mat2=np.array(ri(1,10,9)).reshape(3,3)

print("\n 1st Matrics of Single digit number \n---------------\n",mat1)
print("\n 2st Matrics of Single digit number \n---------------\n",mat2)


 1st Matrics of Single digit number 
---------------
 [[3 1 2]
 [5 8 1]
 [4 8 9]]

 2st Matrics of Single digit number 
---------------
 [[9 3 4]
 [9 9 5]
 [6 2 8]]


In [137]:
print('mat1=\n',mat1)
print('mat2=\n',mat2)

mat1=
 [[3 1 2]
 [5 8 1]
 [4 8 9]]
mat2=
 [[9 3 4]
 [9 9 5]
 [6 2 8]]


In [138]:
print("\n Division \n---------------------\n",mat1/mat2)


 Division 
---------------------
 [[0.33333333 0.33333333 0.5       ]
 [0.55555556 0.88888889 0.2       ]
 [0.66666667 4.         1.125     ]]


In [139]:
print("\n Linear combination : 3*A - 2*B \n",3*mat1-2*mat2)


 Linear combination : 3*A - 2*B 
 [[-9 -3 -2]
 [-3  6 -7]
 [ 0 20 11]]


In [140]:
#Broadcasting-
#Numpy operations are usually dont on pairs of arrays on an element by element basis. in the simplest case, the two arays must have exactly the same shape
# Numpy broadcasting rules relaxex this constraints when the array shape meet certain constraints when operatings on two array,
# Numpy compares their shape element wise it starts with the trailing dimensions ,and word its way forword ,two dimension are compatible
#when they are eqaul,or one of them is 1

In [142]:
start=np.zeros((3,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [143]:
#create a rank1 ndarray with 3 values

In [144]:
add_rows=np.array([[1,0,2]])
print(add_rows)

[[1 0 2]]


In [147]:
y=start+add_rows # add to each row of 'start' using broadcasting

In [146]:
y

array([[1., 0., 2.],
       [1., 0., 2.],
       [1., 0., 2.]])

In [150]:
new_row=add_rows.T # T is use for transpose it convert column into row #vice versa

In [149]:
new_row

array([[1],
       [0],
       [2]])

In [151]:
test=new_row+start
print(test)

[[1. 1. 1.]
 [0. 0. 0.]
 [2. 2. 2.]]


In [152]:
#craete table ndarray which is 4 X 1 to broadcast across coloumn

In [153]:
ad_cols=np.array([[0,2,2,3]])

In [155]:
ad_cols=ad_cols.T

In [156]:
ad_cols

array([[0],
       [2],
       [2],
       [3]])

In [158]:
#Array Math

In [160]:
mat1=np.array(ri(1,10,9)).reshape(3,3)
mat2=np.array(ri(1,10,9)).reshape(3,3)

print("\n 1st Matrix of random single digit number\n---------------------------\n",mat1)
print("\n 2nd Matrix of random single digit number\n---------------------------\n",mat2)

print("\n sq-root of 1st Matrix using np\n",'-'*50,"\n",np.sqrt(mat1))
print("\n square of 2nd Matrix using np\n",'-'*50,"\n",np.square(mat2))


 1st Matrix of random single digit number
---------------------------
 [[8 6 1]
 [4 7 1]
 [5 2 1]]

 2nd Matrix of random single digit number
---------------------------
 [[8 6 4]
 [6 6 3]
 [3 6 4]]

 sq-root of 1st Matrix using np
 -------------------------------------------------- 
 [[2.82842712 2.44948974 1.        ]
 [2.         2.64575131 1.        ]
 [2.23606798 1.41421356 1.        ]]

 square of 2nd Matrix using np
 -------------------------------------------------- 
 [[64 36 16]
 [36 36  9]
 [ 9 36 16]]


In [161]:
#Similarly you can apply other function to matrix to matrix
#please explore more function and practice